version: '3'
services:
  app:
    container_name: app
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/app
    command:
      [
        "--reload",
        "--reload-dir",
        "/app",
        "examples.wsgi:dam.http_server"
      ]
